version: "3"

services:
  db:
    image: postgres
    restart: always
    container_name: postgres-pomodoro
    environment:
      POSTGRES_PASSWORD: pomodoro
      POSTGRES_USER: pomodoro
      POSTGRES_DB: pomodoro
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - pomodoro

networks:
  pomodoro:

volumes:
  postgres:
